name: Node CI/CD Template

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      deploy_path:
        required: true
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm test

      - name: Package artifact
        run: |
          tar -czf app.tar.gz src package.json package-lock.json

      - uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: app.tar.gz

  deploy-dev:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-artifact

      - name: Deploy to DEV EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.tar.gz"
          target: "${{ inputs.deploy_path }}"

      - name: Start app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ inputs.deploy_path }}
            tar -xzf app.tar.gz
            npm install --production
            pm2 delete billing || true
            pm2 start src/index.js --name billing
